 const data={
     employee : [
        {
          id: 1,
          name: "John Smith",
          age: 30,
          position: "Software Engineer",
          department: "IT",
          salary: 60000,
          email: "john.smith@example.com",
          phone: "555-1234",
          hireDate: "2020-01-15",
          address: "123 Main St, City, Country",
          image: "U01",
        },
        {
          id: 2,
          name: "Jane Doe",
          age: 28,
          position: "Data Analyst",
          department: "Data",
          salary: 55000,
          email: "jane.doe@example.com",
          phone: "555-5678",
          hireDate: "2019-03-22",
          address: "456 Oak St, City, Country",
          image: "U02",
        },
        {
          id: 3,
          name: "Michael Johnson",
          age: 35,
          position: "Project Manager",
          department: "Management",
          salary: 75000,
          email: "michael.johnson@example.com",
          phone: "555-8765",
          hireDate: "2018-07-11",
          address: "789 Pine St, City, Country",
          image: "U03",
        },
        {
          id: 4,
          name: "Emily Davis",
          age: 32,
          position: "UX Designer",
          department: "Design",
          salary: 58000,
          email: "emily.davis@example.com",
          phone: "555-4321",
          hireDate: "2021-02-18",
          address: "101 Maple St, City, Country",
          image: "U04",
        },
        {
          id: 5,
          name: "David Brown",
          age: 29,
          position: "Frontend Developer",
          department: "IT",
          salary: 62000,
          email: "david.brown@example.com",
          phone: "555-9102",
          hireDate: "2019-06-05",
          address: "202 Birch St, City, Country",
          image: "U05",
        },
        {
          id: 6,
          name: "Sophia Wilson",
          age: 27,
          position: "HR Specialist",
          department: "HR",
          salary: 50000,
          email: "sophia.wilson@example.com",
          phone: "555-3456",
          hireDate: "2020-09-12",
          address: "303 Cedar St, City, Country",
          image: "U06",
        },
        {
          id: 7,
          name: "Daniel Martinez",
          age: 40,
          position: "Backend Developer",
          department: "IT",
          salary: 68000,
          email: "daniel.martinez@example.com",
          phone: "555-6543",
          hireDate: "2017-04-25",
          address: "404 Elm St, City, Country",
          image: "U07",
        },
        {
          id: 8,
          name: "Olivia Garcia",
          age: 26,
          position: "Marketing Specialist",
          department: "Marketing",
          salary: 54000,
          email: "olivia.garcia@example.com",
          phone: "555-7890",
          hireDate: "2022-01-30",
          address: "505 Walnut St, City, Country",
          image: "U08",
        },
        {
          id: 9,
          name: "Christopher Rodriguez",
          age: 38,
          position: "DevOps Engineer",
          department: "IT",
          salary: 70000,
          email: "christopher.rodriguez@example.com",
          phone: "555-5670",
          hireDate: "2016-08-14",
          address: "606 Chestnut St, City, Country",
          image: "U09",
        },
        {
          id: 10,
          name: "Emma Hernandez",
          age: 31,
          position: "QA Engineer",
          department: "IT",
          salary: 59000,
          email: "emma.hernandez@example.com",
          phone: "555-3210",
          hireDate: "2021-11-07",
          address: "707 Spruce St, City, Country",
          image: "U10",
        },
        {
          id: 11,
          name: "James Lee",
          age: 34,
          position: "Sales Manager",
          department: "Sales",
          salary: 65000,
          email: "james.lee@example.com",
          phone: "555-6789",
          hireDate: "2015-05-23",
          address: "808 Cedar St, City, Country",
          image: "U11",
        },
        {
          id: 12,
          name: "Isabella Thomas",
          age: 29,
          position: "Graphic Designer",
          department: "Design",
          salary: 57000,
          email: "isabella.thomas@example.com",
          phone: "555-4329",
          hireDate: "2019-10-02",
          address: "909 Pine St, City, Country",
          image: "U12",
        },
      ]
 }

 export const GetData=()=>{
        const getUser=data;
        return getUser;
 }